server.port: 8080

management:
  endpoint.health:
    probes.enabled: true
    group:
      liveness:
        show-details: always
      readiness:
        show-details: always
  endpoints.web.exposure.include: health

camel:
  springboot:
    route-controller-supervise-enabled: true
    route-controller-unhealthy-on-exhausted: true
    route-controller-back-off-max-attempts: 3
  component:
    http:
      connect-timeout: 1m
      connection-request-timeout: 1m